# Use the official Tomcat base image
FROM tomcat:latest

# Remove the default ROOT application
RUN rm -rf /usr/local/tomcat/webapps/ROOT

# Copy the .war file to the Tomcat webapps directory
COPY cp /var/lib/jenkins/workspace/docker-tomcat/demo/demo/target/*.war /usr/local/tomcat/webapps/ROOT.war

# Expose the default Tomcat port
EXPOSE 8080